### ISSUE TITLE
good start

### ISSUE THREAD

**Issue by stuydw** [hunter-teacher-cert/currdev_unit_plan-p5_4eva#2]
I like the concept of really focusing on art as a product of computing. Often it's used as a way to demonstrate some particular concept in a visual language (like processing, in fact, I [did this in my class a few weeks ago](https://www.stuycs.org/nextcs-dw/2021/09/24/a05.html) ), so making it the main driving force of the unit is a nice change. The example programs are neat.
I think this will be fine as a four person group. One way in which you could make good use of your numbers is with bringing in real world art examples, like the ones you describe in the proposal. Taking the time to provide artistic background and then using related exercises to emulate that style could prove quite interesting.
Minor note: It wasn't clear in the proposal that p5.js is what you'll be using, it is in the team name and a parenthetical remark in the proposal.

**Comment by mlaks23** [comment]
Should we update the proposal to add more about how we will use p5.js?
